twitter:
  bearer: "AAAAAAAAAAAAAAAAAAAAAM5QxAEAAAAAPdm5po3kIGvr5tXFxcXXu0xDh%2BU%3De8yaYrzrjOVEVkJaCMSkclJdnH1djZamCGLvvSIRtDJpEn3sbU"
  
bluesky:
  handle: "pedrojuuu.bsky.social"
  password: "pkc7-o43c-ksbw-zhmr"