twitter:
  bearer: "AAAAAAAAAAAAAAAAAAAAAM5QxAEAAAAAPdm5po3kIGvr5tXFxcXXu0xDh%2BU%3De8yaYrzrjOVEVkJaCMSkclJdnH1djZamCGLvvSIRtDJpEn3sbU"
  
bluesky:
  handle: "pedrojuuu.bsky.social"
  password: "eyJ0eXAiOiJhdCtqd3QiLCJhbGciOiJFUzI1NksifQ.eyJzY29wZSI6ImNvbS5hdHByb3RvLmFwcFBhc3MiLCJzdWIiOiJkaWQ6cGxjOnJ2Y3JucnE3cjc2dmJmZnhqZGs0dGh3ZiIsImlhdCI6MTczMjEwNDkzOSwiZXhwIjoxNzMyMTEyMTM5LCJhdWQiOiJkaWQ6d2ViOnB1ZmZiYWxsLnVzLWVhc3QuaG9zdC5ic2t5Lm5ldHdvcmsifQ.pxJl82-dBQZyjnb7JKOmXgyXf1FD0XDtjdme4YsHVF-5z1aemm1RclcyaBGnvbrCyUpQO0wb5xwyD0r19cIbyg"