twitter:
  bearer: "AAAAAAAAAAAAAAAAAAAAAM5QxAEAAAAAPdm5po3kIGvr5tXFxcXXu0xDh%2BU%3De8yaYrzrjOVEVkJaCMSkclJdnH1djZamCGLvvSIRtDJpEn3sbU"
  
bluesky:
  username: "pedrojuuu.bsky.social"
  apppassword: "3lcs-qimp-kvi3-2gvl"